apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 4.39.0
    chart: prometheus-node-exporter
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
